#version: '3'
version: '2.1'

services:

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - $PWD/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/config/conf.d:/etc/nginx/conf.d:ro
      - $PWD/certs:/CERTS
      - $PWD/html/error:/var/www/error:ro
      - $PWD/html/img:/var/www/img:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - default
      - backend
    mem_limit: 128M
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
  default:
    name: proxy_frontend
    driver: bridge
  backend:
